name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: claraparabricks/cromwell

    steps:
    - uses: actions/checkout@v3
      
    - name: validate
      run: make validate
